version: "3.7"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root

    ports:
      - 3307:3306

    volumes:
      - /home/mysql/data:/var/lib/mysql

